<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>DeathBox</RootNamespace>
    <AssemblyName>RustDeathBox</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Unturned_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Unturned_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="Rocket.API">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Extras\Rocket.Unturned\Rocket.API.dll</HintPath>
    </Reference>
    <Reference Include="Rocket.Core">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Extras\Rocket.Unturned\Rocket.Core.dll</HintPath>
    </Reference>
    <Reference Include="Rocket.Unturned">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Extras\Rocket.Unturned\Rocket.Unturned.dll</HintPath>
    </Reference>
    <Reference Include="SDG.NetTransport">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Unturned_Data\Managed\SDG.NetTransport.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>C:\SteamCMD\steamapps\common\U3DS\Unturned_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="SET &quot;sourcedir=$(OutDir)&#xD;&#xA;XCOPY /v /y &quot;%25sourcedir%25\$(AssemblyName).dll*&quot; &quot;..\DLLs\$(AssemblyName).dll*&quot;&#xD;&#xA;" />
  </Target>

</Project>
